config/routes.rb
Rails.application.routes.draw do
  devise_for :teachers
  resources :subjects
  resources :subject_categories
  get 'welcome/index'
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :subject_category
end

app/models/subject_category.rb
class SubjectCategory < ApplicationRecord
	has_many :subjects
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/subject_categories_controller.rb
class SubjectCategoriesController < ApplicationController
  before_action :set_subject_category, only: [:show, :edit, :update, :destroy]

  # GET /subject_categories
  # GET /subject_categories.json
  def index
    @subject_categories = SubjectCategory.all
  end

  # GET /subject_categories/1
  # GET /subject_categories/1.json
  def show
  end

  # GET /subject_categories/new
  def new
    @subject_category = SubjectCategory.new
  end

  # GET /subject_categories/1/edit
  def edit
  end

  # POST /subject_categories
  # POST /subject_categories.json
  def create
    @subject_category = SubjectCategory.new(subject_category_params)

    respond_to do |format|
      if @subject_category.save
        format.html { redirect_to @subject_category, notice: 'Subject category was successfully created.' }
        format.json { render :show, status: :created, location: @subject_category }
      else
        format.html { render :new }
        format.json { render json: @subject_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subject_categories/1
  # PATCH/PUT /subject_categories/1.json
  def update
    respond_to do |format|
      if @subject_category.update(subject_category_params)
        format.html { redirect_to @subject_category, notice: 'Subject category was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject_category }
      else
        format.html { render :edit }
        format.json { render json: @subject_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subject_categories/1
  # DELETE /subject_categories/1.json
  def destroy
    @subject_category.destroy
    respond_to do |format|
      format.html { redirect_to subject_categories_url, notice: 'Subject category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject_category
      @subject_category = SubjectCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_category_params
      params.require(:subject_category).permit(:name, :description)
    end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  # GET /subjects
  # GET /subjects.json
  def index
  @q = Subject.ransack(params[:q])
  @subjects = @q.result(distinct: true)
end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:name, :description, :subject_category_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subject_categories_helper.rb
module SubjectCategoriesHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TutorApp" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
   

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">TutorApp</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/subject_categories/_form.html.erb
<%= form_for @subject_category, :html => { :class => "form-horizontal subject_category" } do |f| %>

  <% if @subject_category.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@subject_category.errors.count, "error") %> prohibited this subject_category from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @subject_category.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                subject_categories_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/subject_categories/edit.html.erb
<%- model_class = SubjectCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/subject_categories/index.html.erb
<%- model_class = SubjectCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @subject_categories.each do |subject_category| %>
      <tr>
        <td><%= link_to subject_category.id, subject_category_path(subject_category) %></td>
        <td><%= subject_category.name %></td>
        <td><%= subject_category.description %></td>
        <td><%=l subject_category.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      subject_category_path(subject_category), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_subject_category_path(subject_category), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      subject_category_path(subject_category),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_subject_category_path,
            :class => 'btn btn-primary' %>
            <%= link_to t('.subjects', :default => t("helpers.links.back_to_sub")),
              subjects_path, :class => 'btn btn-default'  %>

app/views/subject_categories/new.html.erb
<%- model_class = SubjectCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/subject_categories/show.html.erb
<%- model_class = SubjectCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @subject_category.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @subject_category.description %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              subject_categories_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_subject_category_path(@subject_category), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              subject_category_path(@subject_category),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
              

app/views/subjects/_form.html.erb
<%= form_for @subject, :html => { :class => "form-horizontal subject" } do |f| %>

  <% if @subject.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@subject.errors.count, "error") %> prohibited this subject from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @subject.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
  
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>
  <div class="form-group">
    <%= f.label :subject_category_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :subject_category_id,options_for_select(SubjectCategory.all.collect{|c| [c.name, c.id]}), {prompt: "Select Category"}, {:class => 'form-control'} %>
    </div>
    <%=f.error_span(:subject_category_id) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                subjects_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<%- model_class = Subject -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/subjects/index.html.erb
<%- model_class = Subject -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<%= search_form_for @q do |f| %>

  
  
  <%= f.search_field :name_cont %>

  
  <%= f.submit %>
<% end %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:subject_category_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= link_to subject.id, subject_path(subject) %></td>
        <td><%= subject.name %></td>
        <td><%= subject.description %></td>
        <td><%= subject.subject_category_id %></td>
        <td><%=l subject.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      subject_path(subject), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_subject_path(subject), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      subject_path(subject),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_subject_path,
            :class => 'btn btn-primary' %>
            <%= link_to t('.subjects', :default => t("helpers.links.back_to_sub_cat")),
              subject_categories_path, :class => 'btn btn-default'  %>

app/views/subjects/new.html.erb
<%- model_class = Subject -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/subjects/show.html.erb
<%- model_class = Subject -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @subject.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @subject.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:subject_category_id) %>:</strong></dt>
  <dd><%= @subject.subject_category_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              subjects_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_subject_path(@subject), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              subject_path(@subject),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/welcome/index.html.erb
<h1>Tutor-App</h1>
 <%= link_to t('.subjects', :default => t("helpers.links.Add_Subjects")),
              subjects_path, :class => 'btn btn-default'  %>

 <%= link_to t('.subjects', :default => t("helpers.links.Add_categories")),
              subject_categories_path, :class => 'btn btn-default'  %>

 <%= link_to t('.subjects', :default => t("helpers.links.SignUp")),
              new_teacher_session_path, :class => 'btn btn-default'  %>